myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns(
 path(_('admin/'), admin.site.urls),
 path(_('cart/'), include('cart.urls', namespace='cart')),
 path(_('orders/'), include('orders.urls', namespace='orders')),
 path(_('payment/'), include('payment.urls', namespace='payment')),
 path(_('coupons/'), include('coupons.urls', namespace='coupons')),
 path('rosetta/', include('rosetta.urls')),
 path('', include('shop.urls', namespace='shop')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _


app_name = 'orders'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    # After building the product list and detail views, we have to define URL patterns for them
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, 
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]





# We have defined two different URL patterns for the product_list view: a pattern named
# product_list, which calls the product_list view without any parameters; and a pattern named
# product_list_by_category, which provides a category_slug parameter to the view for filtering
# products according to a given category. We added a pattern for the product_detail view, which
# passes the id and slug parameters to the view in order to retrieve a specific product.

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
# quantity: This allows the user to select a quantity between 1-20. We use a TypedChoiceField field with coerce=int to convert the input into an integer.

# update: This allows you to indicate whether the quantity has to be added to any existing quantity in the cart for this product (False), or whether the existing quantity has to be updated with the given quantity (True).
# We use a HiddenInput widget for this field since we don't want to display it to the user.


from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int,
                                label=_('Quantity'))
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm # include the coupon system in the cart's detail view
from shop.recommender import Recommender


# adding products to the cart or updating quantities for existing products.
# We use the require_POST decorator to allow only POST requests, since this
# view is going to change data. The view receives the product ID as a parameter.
# We retrieve the Product instance with the given ID and validate CartAddProductForm.
# If the form is valid, we either add or update the product in the cart.
# The view redirects to the cart_detail URL that will display the content of the cart.



@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


# remove items from the cart

# cart_remove view receives the product ID as a parameter. We retrieve the Product instance
# with the given ID and remove the product from the cart. Then, we redirect the user to the cart_detail URL.
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

# display the cart and its items
def cart_detail(request):
    cart = Cart(request)
    
    # allow users to change quantities from the cart detail page.
    for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                              initial={'quantity': item['quantity'],
                              'update': True})

    coupon_apply_form = CouponApplyForm()

    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended_products = r.suggest_products_for(cart_products,
                                                  max_results=4)

    return render(request,
                  'cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form,
                   'recommended_products': recommended_products})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans "Your shopping cart" %}
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="mb-4">{% trans "Your shopping cart" %}</h1>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">{% trans "Product" %}</th>
            <th scope="col">{% trans "Quantity" %}</th>
            <th scope="col">{% trans "Remove" %}</th>
            <th scope="col">{% trans "Unit price" %}</th>
            <th scope="col">{% trans "Price" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
            {% with product=item.product %}
              <tr>
                <td>
                  <div>
                    <h5>{{ product.name }}</h5>
                    <p>{% trans "Category" %}: {{ product.category }}</p>
                  </div>
                </td>
                <td>
                  <form action="{% url "cart:cart_add" product.id %}" method="post">
                    <div class="input-group">
                      {{ item.update_quantity_form.quantity }}
                      <!-- <button type="submit" class="btn btn-sm btn-primary ms-2">{{ item.update_quantity_form.update }}</button> -->
                      <button type="submit" class="btn btn-sm btn-primary ms-2" title="{% trans 'Update' %}">
                        {{ item.update_quantity_form.update }}<i class="fas fa-sync-alt"></i>  <!-- Font Awesome icon for update -->
                      </button>
                      {% csrf_token %}
                    </div>
                  </form>
                </td>
                <td>
                  <a href="{% url "cart:cart_remove" product.id %}" class="btn btn-sm btn-danger">{% trans "Remove" %}</a>
                  <!-- <a href="{% url 'cart:cart_remove' product.id %}" class="btn btn-sm btn-danger" title="{% trans 'Remove' %}">
                    <i class="fas fa-trash-alt"></i>
                  </a> -->
                </td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
              </tr>
            {% endwith %}
          {% endfor %}
          {% if cart.coupon %}
            <tr class="subtotal">
              <td colspan="4">{% trans "Subtotal" %}</td>
              <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
            </tr>
            <tr>
              {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
                <td colspan="4">"{{ code }}" coupon ({{ discount }}% off)</td>
              {% endblocktrans %}
              <td class="num neg">
                - ${{ cart.get_discount|floatformat:"2" }}
              </td>
            </tr>
          {% endif %}
          <tr class="total">
            <td colspan="4">{% trans "Total" %}</td>
            <td class="num">
              ${{ cart.get_total_price_after_discount|floatformat:"2" }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    {% if recommended_products %}
      <div class="recommendations">
        <h3 class="mb-4">{% trans "People who bought this also bought" %}</h3>
        <div class="row row-cols-1 row-cols-md-3 g-3">
          {% for p in recommended_products %}
            <div class="col">
              <div class="card h-100">
                <div class="card-body">
                  <h5 class="card-title"><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></h5>
                  <p class="card-text">{% trans "Category" %}: {{ p.category }}</p>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}
    <hr>
    <div class="row">
      <div class="col-md-6">
        <p>{% trans "Apply a coupon" %}:</p>
        <form action="{% url "coupons:apply" %}" method="post">
          <div class="input-group mb-3">
            {{ coupon_apply_form }}
            <button type="submit" class="btn btn-outline-primary">{% trans "Apply" %}</button>
            {% csrf_token %}
          </div>
        </form>
      </div>
      <div class="col-md-6 d-flex justify-content-md-end align-items-center">
        <a href="{% url "shop:product_list" %}" class="btn btn-light me-3">{% trans "Continue shopping" %}</a>
        <a href="{% url "orders:order_create" %}" class="btn btn-primary">{% trans "Checkout" %}</a>
      </div>
    </div>
  </div>
{% endblock %}